
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    # Reinicia automáticamente si falla
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Le decimos que espere a que el backend exista para prenderse
    depends_on:
      - backend